version: '3.9'
services:
  primer-three:
    container_name: primer-three
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    tty: true
    ports:
      - '3000:3000'
